#github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: mukeshsolanki
open_collective: mukesh-solanki
ko_fi: mukeshsolanki
liberapay: mukeshsolanki
issuehunt: mukeshsolanki
custom: https://www.paypal.me/mukeshsolanki
